baseURL = "https://cryptosrus.lol"
title = "CRYPTORUS DOT LOL | For all the crypto memes!"
description = ""
author = "CRYPTORUS.LOL"
paginate = 7
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
googleAnalytics = ""
disqusShortname = ""
theme = "simplog"

[menu]
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "upload"
    name = "Upload Meme"
    url = "/sube/"
    weight = 30

[taxonomies]
  category = "categories"
  tag = "tags"
  archive = "archives"

[params]
  subtitle = "Humor crypto para pasar el invierno"
  colorTheme = "dark"
  description = "crypto-memes para el mundo"
  twitter = "elaltquimista"
  customCSS = ""
  adobeFontsKitId = ""

  [params.enabled]
    comment = true
    summary = true
    toc = true
